name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./gradlew :backend:build
      - name: Prepare BootJar
        run: ./gradlew bootJar
      - name: Deploy
        run: ./gradlew deployHeroku
        env:
          HEROKU_API_KEY: "${{ secrets.HEROKU_API_KEY }}"
