name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: ./gradlew :backend:build :backend:bootJar && ./gradlew :backend:deployHeroku
        env:
          HEROKU_API_KEY: "${{ secrets.HEROKU_API_KEY }}"