name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Standard build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Assemble
        run: ./gradlew assemble
      - name: Check backend
        run: ./gradlew :backend:check
      - name: Check app
        run: ./gradlew :app:check
      - name: Save fail app test reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: core-test-reports
          path: app/build/reports/tests/test/